<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MapDriveWorker</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JoltPhysicsSharp" Version="[2.22.0]" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../../server/physics/Program.cs" />
    <Compile Include="../../server/physics/CheckedInput.cs" />
  </ItemGroup>
</Project>
