using System.Numerics;
using System.Text.Json;
using JoltPhysicsSharp;
using MapDrive;

// Explicit test_lab dynamics, not a historical reconstruction. All state is
// generated by this process from imported static geometry and domain inputs.
try
{
    if (args.Length != 6 || args[0] != "--local-root" || args[2] != "--config" || args[4] != "--config-sha256")
        throw new InvalidDataException("expected --local-root PATH --config PATH --config-sha256 SHA256");
    string root = Path.GetFullPath(args[1]), hash = args[5];
    if (hash.Length != 64 || hash.Any(c => !"0123456789abcdef".Contains(c))) throw new InvalidDataException("config hash required");
    using var config = CheckedInput.Json(CheckedInput.FileBytes(CheckedInput.Owned(root, args[3]), 16384, hash));
    var c = config.RootElement;
    CheckedInput.Fields(c, "version", "profile", "map", "terrain", "obstacles", "spawn_origin", "spawn_yaw",
        "body_half_extents", "body_center_offset", "wheel_points", "mass_kg", "max_forward_mps", "max_reverse_mps",
        "engine_max_torque_nm", "wheel_radius", "suspension_min", "suspension_max", "track_max_brake_torque", "bounds_xz");
    if (c.GetProperty("version").GetInt32() != 1 || c.GetProperty("profile").GetString() != "test_lab")
        throw new InvalidDataException("only explicit test_lab v1 supported");
    string map = c.GetProperty("map").GetString()!;
    if (map is not ("01_karelia" or "05_prohorovka")) throw new InvalidDataException("map outside checked pool");
    var spawn = CheckedInput.Vector(c.GetProperty("spawn_origin"), -1000, 1000);
    var half = CheckedInput.Vector(c.GetProperty("body_half_extents"), .1f, 5);
    var center = CheckedInput.Vector(c.GetProperty("body_center_offset"), -5, 5);
    float N(string key, float low, float high) => CheckedInput.Number(c.GetProperty(key), low, high);
    float yaw = N("spawn_yaw", -MathF.PI, MathF.PI), mass = N("mass_kg", 1000, 100000);
    float forwardLimit = N("max_forward_mps", 1, 20), reverseLimit = N("max_reverse_mps", .5f, 10);
    float radius = N("wheel_radius", .05f, 1), suspensionMin = N("suspension_min", 0, 1);
    float suspensionMax = N("suspension_max", .05f, 1);
    if (suspensionMax <= suspensionMin) throw new InvalidDataException("suspension range empty");
    var points = c.GetProperty("wheel_points");
    if (points.ValueKind != JsonValueKind.Array || points.GetArrayLength() != 6) throw new InvalidDataException("six support points required");
    var wheelPoints = points.EnumerateArray().Select(v => CheckedInput.Vector(v, -5, 5)).ToArray();
    var bounds = c.GetProperty("bounds_xz");
    if (bounds.GetArrayLength() != 4) throw new InvalidDataException("four bounds required");
    float minX = CheckedInput.Number(bounds[0], -1000, 0), minZ = CheckedInput.Number(bounds[1], -1000, 0);
    float maxX = CheckedInput.Number(bounds[2], 0, 1000), maxZ = CheckedInput.Number(bounds[3], 0, 1000);
    if (maxX - minX < 100 || maxZ - minZ < 100 || spawn.X < minX + 5 || spawn.X > maxX - 5 ||
        spawn.Z < minZ + 5 || spawn.Z > maxZ - 5) throw new InvalidDataException("spawn outside usable map");

    if (!Foundation.Init(false)) throw new InvalidOperationException("Jolt initialization failed");
    try
    {
        using var pairs = new ObjectLayerPairFilterTable(2);
        pairs.EnableCollision(0, 1); pairs.EnableCollision(1, 1);
        using var broad = new BroadPhaseLayerInterfaceTable(2, 2);
        broad.MapObjectToBroadPhaseLayer(0, 0); broad.MapObjectToBroadPhaseLayer(1, 1);
        using var filter = new ObjectVsBroadPhaseLayerFilterTable(broad, 2, pairs, 2);
        using var jobs = new JobSystemThreadPool();
        using var world = new PhysicsSystem(new PhysicsSystemSettings {
            MaxBodies = 32, MaxBodyPairs = 1024, MaxContactConstraints = 1024,
            ObjectLayerPairFilter = pairs, BroadPhaseLayerInterface = broad, ObjectVsBroadPhaseLayerFilter = filter });
        var bodies = world.BodyInterface;
        var staticBodies = new List<BodyID>();
        using var terrain = CheckedInput.LoadMesh(root, c.GetProperty("terrain"), map);
        using var obstacles = CheckedInput.LoadMesh(root, c.GetProperty("obstacles"), map);
        void AddStatic(Shape shape, Vector3 position)
        {
            using var creation = new BodyCreationSettings(shape, position, Quaternion.Identity, MotionType.Static, 0) { Friction = 1 };
            var created = bodies.CreateBody(creation);
            bodies.AddBody(created.ID, Activation.DontActivate); staticBodies.Add(created.ID);
        }
        AddStatic(terrain, Vector3.Zero); AddStatic(obstacles, Vector3.Zero);
        // Domain boundaries are explicit server walls, independent of mesh collar.
        using var xWall = new BoxShape(new Vector3(.5f, 500, (maxZ - minZ) / 2 + 1));
        using var zWall = new BoxShape(new Vector3((maxX - minX) / 2 + 1, 500, .5f));
        AddStatic(xWall, new(minX - .5f, 0, (maxZ + minZ) / 2));
        AddStatic(xWall, new(maxX + .5f, 0, (maxZ + minZ) / 2));
        AddStatic(zWall, new((maxX + minX) / 2, 0, minZ - .5f));
        AddStatic(zWall, new((maxX + minX) / 2, 0, maxZ + .5f));
        var rotation = Quaternion.CreateFromAxisAngle(Vector3.UnitY, yaw);
        using var bodyShape = new BoxShape(half);
        using var bodySettings = new BodyCreationSettings(bodyShape, spawn + Vector3.Transform(center, rotation), rotation, MotionType.Dynamic, 1) {
            OverrideMassProperties = OverrideMassProperties.CalculateInertia, MassPropertiesOverride = new MassProperties { Mass = mass },
            AllowSleeping = false, MaxLinearVelocity = 25, Friction = 1 };
        var body = bodies.CreateBody(bodySettings); bodies.AddBody(body.ID, Activation.Activate);
        var wheels = wheelPoints.Select(p => new WheelSettingsTV {
            Position = p - center, SuspensionDirection = -Vector3.UnitY, WheelUp = Vector3.UnitY, WheelForward = Vector3.UnitZ,
            SuspensionMinLength = suspensionMin, SuspensionMaxLength = suspensionMax, Radius = radius, Width = .25f,
            LongitudinalFriction = 1.2f, LateralFriction = 1.2f,
            SuspensionSpring = new SpringSettings(SpringMode.FrequencyAndDamping, 2, .7f) }).ToArray();
        using var controllerSettings = new TrackedVehicleControllerSettings();
        var engine = controllerSettings.Engine; engine.MaxTorque = N("engine_max_torque_nm", 10, 10000); controllerSettings.Engine = engine;
        float brakeTorque = N("track_max_brake_torque", 100, 100000);
        controllerSettings.SetTrack(0, new VehicleTrackSettings { DrivenWheel = 1, Wheels = [0, 1, 2], MaxBrakeTorque = brakeTorque });
        controllerSettings.SetTrack(1, new VehicleTrackSettings { DrivenWheel = 4, Wheels = [3, 4, 5], MaxBrakeTorque = brakeTorque });
        using var constraint = new VehicleConstraint(body, new VehicleConstraintSettings {
            Up = Vector3.UnitY, Forward = Vector3.UnitZ, Wheels = wheels, Controller = controllerSettings, MaxPitchRollAngle = MathF.PI / 3 });
        using var tester = new VehicleCollisionTesterRay(1);
        constraint.SetVehicleCollisionTester(tester); world.AddConstraint(constraint); world.AddStepListener(constraint);
        var controller = constraint.GetController<TrackedVehicleController>();
        long tick = 0, sequence = 0;
        var contactMasks = new Queue<int>(6);
        try
        {
            world.OptimizeBroadPhase();
            void Advance(int throttle, int steer, bool brake, int count)
            {
                for (int i = 0; i < count; i++)
                {
                    var q = bodies.GetRotation(body.ID);
                    float speed = Vector3.Dot(bodies.GetLinearVelocity(body.ID), Vector3.Transform(Vector3.UnitZ, q));
                    float motor = throttle;
                    if ((throttle > 0 && speed >= forwardLimit) || (throttle < 0 && speed <= -reverseLimit)) motor = 0;
                    float left = 1, right = 1;
                    if (steer != 0)
                    {
                        if (throttle == 0) { motor = 1; left = steer; right = -steer; }
                        else if (steer > 0) right = .2f;
                        else left = .2f;
                    }
                    controller.SetDriverInput(motor, left, right, brake ? 1 : 0);
                    var error = world.Update(1f / 60, 1, jobs);
                    if (error != PhysicsUpdateError.None) throw new InvalidOperationException("physics capacity exceeded");
                    tick++;
                    int mask = 0;
                    for (int wheel = 0; wheel < 6; wheel++)
                        if (constraint.GetWheel(wheel).HasContact) mask |= 1 << wheel;
                    if (contactMasks.Count == 6) contactMasks.Dequeue();
                    contactMasks.Enqueue(mask);
                    var pos = bodies.GetPosition(body.ID);
                    if (!float.IsFinite(pos.X) || !float.IsFinite(pos.Y) || !float.IsFinite(pos.Z) || pos.Y < -100 || pos.Y > 500 ||
                        pos.X < minX - 1 || pos.X > maxX + 1 || pos.Z < minZ - 1 || pos.Z > maxZ + 1)
                        throw new InvalidOperationException("authoritative body outside bounds");
                }
            }
            object State()
            {
                var q = bodies.GetRotation(body.ID);
                var origin = bodies.GetPosition(body.ID) - Vector3.Transform(center, q);
                var velocity = bodies.GetLinearVelocity(body.ID); var angular = bodies.GetAngularVelocity(body.ID);
                var forward = Vector3.Transform(Vector3.UnitZ, q); var right = Vector3.Transform(Vector3.UnitX, q); var up = Vector3.Transform(Vector3.UnitY, q);
                float[] V(Vector3 v) => [v.X, v.Y, v.Z];
                return new { position = V(origin), direction = new[] { MathF.Atan2(forward.X, forward.Z), MathF.Asin(Math.Clamp(-forward.Y, -1, 1)), MathF.Atan2(right.Y, up.Y) },
                    speed = Vector3.Dot(velocity, forward), rspeed = angular.Y, contacts = Enumerable.Range(0, 6).Count(i => constraint.GetWheel(i).HasContact),
                    linear_velocity = V(velocity), angular_velocity = V(angular), wheel_contact_masks = contactMasks.ToArray() };
            }
            void Write(string eventName) => Console.WriteLine(JsonSerializer.Serialize(new { version = 1, @event = eventName, seq = sequence,
                tick, settle_ticks = 180, map, config_sha256 = hash, state = State() }));
            Advance(0, 0, true, 180);
            if (Enumerable.Range(0, 6).Count(i => constraint.GetWheel(i).HasContact) < 3 || bodies.GetLinearVelocity(body.ID).Length() > 1)
                throw new InvalidOperationException("spawn failed to settle on imported geometry");
            Write("ready");
            using var input = Console.OpenStandardInput();
            for (byte[]? line; (line = CheckedInput.ReadLine(input)) != null;)
            {
                using var command = CheckedInput.Json(line);
                var request = command.RootElement;
                CheckedInput.Fields(request, "version", "op", "seq", "ticks", "input");
                if (request.GetProperty("version").GetInt32() != 1 || request.GetProperty("op").GetString() != "advance" ||
                    request.GetProperty("seq").GetInt64() != sequence + 1 || sequence >= 36000 || request.GetProperty("ticks").GetInt32() != 6)
                    throw new InvalidDataException("IPC sequence or cadence mismatch");
                var controls = request.GetProperty("input"); CheckedInput.Fields(controls, "throttle", "steer", "brake");
                int throttle = controls.GetProperty("throttle").GetInt32(), steer = controls.GetProperty("steer").GetInt32();
                bool brake = controls.GetProperty("brake").GetBoolean();
                if (Math.Abs((long)throttle) > 1 || Math.Abs((long)steer) > 1 || (brake && (throttle != 0 || steer != 0)))
                    throw new InvalidDataException("invalid domain driving input");
                Advance(throttle, steer, brake, 6); sequence++; Write("state");
            }
        }
        finally
        {
            world.RemoveStepListener(constraint); world.RemoveConstraint(constraint);
            bodies.RemoveAndDestroyBody(body.ID);
            foreach (var id in staticBodies) bodies.RemoveAndDestroyBody(id);
            foreach (var wheel in wheels) wheel.Dispose();
        }
    }
    finally { Foundation.Shutdown(); }
    return 0;
}
catch (Exception error)
{
    // Failure is visible to the parent, never returned as a valid state.
    Console.Error.WriteLine(JsonSerializer.Serialize(new { @event = "worker_error", type = error.GetType().Name, message = error.Message }));
    return 1;
}
